# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_grafica.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(437, 443)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 3, 0, 1, 5)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.pushButton_cargarDir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cargarDir.setObjectName("pushButton_cargarDir")
        self.gridLayout_5.addWidget(self.pushButton_cargarDir, 1, 3, 1, 1)
        self.lineEdit_direccion = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_direccion.setObjectName("lineEdit_direccion")
        self.gridLayout_5.addWidget(self.lineEdit_direccion, 1, 1, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 5)
        self.label_nombreArchivoCSV = QtWidgets.QLabel(self.centralwidget)
        self.label_nombreArchivoCSV.setObjectName("label_nombreArchivoCSV")
        self.gridLayout_5.addWidget(self.label_nombreArchivoCSV, 2, 1, 1, 1)
        self.pushButton_examDir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_examDir.setObjectName("pushButton_examDir")
        self.gridLayout_5.addWidget(self.pushButton_examDir, 1, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_CargarLabelsMedias = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_CargarLabelsMedias.setObjectName("pushButton_CargarLabelsMedias")
        self.gridLayout.addWidget(self.pushButton_CargarLabelsMedias, 2, 0, 1, 1)
        self.pushButton_LimparLabelsMedias = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_LimparLabelsMedias.setObjectName("pushButton_LimparLabelsMedias")
        self.gridLayout.addWidget(self.pushButton_LimparLabelsMedias, 2, 1, 1, 1)
        self.groupBox_gps = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_gps.setObjectName("groupBox_gps")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_gps)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_gps)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_gps)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_gps)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_gps)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_gps_PosicionMedia = QtWidgets.QLabel(self.groupBox_gps)
        self.label_gps_PosicionMedia.setObjectName("label_gps_PosicionMedia")
        self.gridLayout_3.addWidget(self.label_gps_PosicionMedia, 0, 1, 1, 1)
        self.label_gps_dato2 = QtWidgets.QLabel(self.groupBox_gps)
        self.label_gps_dato2.setObjectName("label_gps_dato2")
        self.gridLayout_3.addWidget(self.label_gps_dato2, 1, 1, 1, 1)
        self.label_gps_dato3 = QtWidgets.QLabel(self.groupBox_gps)
        self.label_gps_dato3.setObjectName("label_gps_dato3")
        self.gridLayout_3.addWidget(self.label_gps_dato3, 2, 1, 1, 1)
        self.label_gps_dato4 = QtWidgets.QLabel(self.groupBox_gps)
        self.label_gps_dato4.setObjectName("label_gps_dato4")
        self.gridLayout_3.addWidget(self.label_gps_dato4, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_gps, 1, 0, 1, 2)
        self.groupBox_acc = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_acc.setObjectName("groupBox_acc")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_acc)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_acc)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_acc)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_acc)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_acc_AceleracionMedia = QtWidgets.QLabel(self.groupBox_acc)
        self.label_acc_AceleracionMedia.setObjectName("label_acc_AceleracionMedia")
        self.gridLayout_2.addWidget(self.label_acc_AceleracionMedia, 0, 1, 1, 1)
        self.label_acc_PosicionMedia = QtWidgets.QLabel(self.groupBox_acc)
        self.label_acc_PosicionMedia.setObjectName("label_acc_PosicionMedia")
        self.gridLayout_2.addWidget(self.label_acc_PosicionMedia, 3, 1, 1, 1)
        self.label_acc_VelocidadMedia = QtWidgets.QLabel(self.groupBox_acc)
        self.label_acc_VelocidadMedia.setObjectName("label_acc_VelocidadMedia")
        self.gridLayout_2.addWidget(self.label_acc_VelocidadMedia, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_acc, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton_Graficar_PosVsTiempo = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_Graficar_PosVsTiempo.setObjectName("pushButton_Graficar_PosVsTiempo")
        self.gridLayout_6.addWidget(self.pushButton_Graficar_PosVsTiempo, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 3, 0, 1, 1)
        self.pushButton_Graficar_VelVsTiempo = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_Graficar_VelVsTiempo.setObjectName("pushButton_Graficar_VelVsTiempo")
        self.gridLayout_6.addWidget(self.pushButton_Graficar_VelVsTiempo, 2, 1, 1, 1)
        self.pushButton_Graficar_AccVsTiempo = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_Graficar_AccVsTiempo.setObjectName("pushButton_Graficar_AccVsTiempo")
        self.gridLayout_6.addWidget(self.pushButton_Graficar_AccVsTiempo, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 4, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 5, 0, 1, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_5.addWidget(self.tabWidget, 4, 0, 1, 5)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 437, 20))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuConectar = QtWidgets.QMenu(self.menubar)
        self.menuConectar.setObjectName("menuConectar")
        self.menuVer = QtWidgets.QMenu(self.menubar)
        self.menuVer.setObjectName("menuVer")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuAcerca_del_proyecto = QtWidgets.QMenu(self.menuAyuda)
        self.menuAcerca_del_proyecto.setObjectName("menuAcerca_del_proyecto")
        self.menuManuales = QtWidgets.QMenu(self.menuAyuda)
        self.menuManuales.setObjectName("menuManuales")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(mainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionExportar_Datos = QtWidgets.QAction(mainWindow)
        self.actionExportar_Datos.setObjectName("actionExportar_Datos")
        self.actionImportar_CSV = QtWidgets.QAction(mainWindow)
        self.actionImportar_CSV.setObjectName("actionImportar_CSV")
        self.actionMinimizar = QtWidgets.QAction(mainWindow)
        self.actionMinimizar.setObjectName("actionMinimizar")
        self.actionTamanio_Completo = QtWidgets.QAction(mainWindow)
        self.actionTamanio_Completo.setObjectName("actionTamanio_Completo")
        self.actionExportar_Graficas = QtWidgets.QAction(mainWindow)
        self.actionExportar_Graficas.setObjectName("actionExportar_Graficas")
        self.actionIr_a_carpeta_fuente = QtWidgets.QAction(mainWindow)
        self.actionIr_a_carpeta_fuente.setObjectName("actionIr_a_carpeta_fuente")
        self.actionManual_de_usuario = QtWidgets.QAction(mainWindow)
        self.actionManual_de_usuario.setObjectName("actionManual_de_usuario")
        self.actionIdea_Fuerza = QtWidgets.QAction(mainWindow)
        self.actionIdea_Fuerza.setObjectName("actionIdea_Fuerza")
        self.actionInforme = QtWidgets.QAction(mainWindow)
        self.actionInforme.setObjectName("actionInforme")
        self.actionIr_carpeta_fuente = QtWidgets.QAction(mainWindow)
        self.actionIr_carpeta_fuente.setObjectName("actionIr_carpeta_fuente")
        self.actionNotas = QtWidgets.QAction(mainWindow)
        self.actionNotas.setObjectName("actionNotas")
        self.actionManual_tecnico = QtWidgets.QAction(mainWindow)
        self.actionManual_tecnico.setObjectName("actionManual_tecnico")
        self.actionManual_de_app = QtWidgets.QAction(mainWindow)
        self.actionManual_de_app.setObjectName("actionManual_de_app")
        self.actionConfiguracion = QtWidgets.QAction(mainWindow)
        self.actionConfiguracion.setObjectName("actionConfiguracion")
        self.actionEjemplo_de_formato_csv = QtWidgets.QAction(mainWindow)
        self.actionEjemplo_de_formato_csv.setObjectName("actionEjemplo_de_formato_csv")
        self.actionFormato_del_CSV = QtWidgets.QAction(mainWindow)
        self.actionFormato_del_CSV.setObjectName("actionFormato_del_CSV")
        self.menuArchivo.addAction(self.actionImportar_CSV)
        self.menuArchivo.addAction(self.actionExportar_Datos)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionExportar_Graficas)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuVer.addAction(self.actionTamanio_Completo)
        self.menuVer.addAction(self.actionMinimizar)
        self.menuVer.addSeparator()
        self.menuVer.addAction(self.actionConfiguracion)
        self.menuVer.addSeparator()
        self.menuAcerca_del_proyecto.addAction(self.actionIdea_Fuerza)
        self.menuAcerca_del_proyecto.addAction(self.actionInforme)
        self.menuAcerca_del_proyecto.addAction(self.actionIr_carpeta_fuente)
        self.menuAcerca_del_proyecto.addSeparator()
        self.menuAcerca_del_proyecto.addAction(self.actionNotas)
        self.menuManuales.addAction(self.actionManual_de_app)
        self.menuManuales.addSeparator()
        self.menuManuales.addAction(self.actionManual_de_usuario)
        self.menuManuales.addAction(self.actionManual_tecnico)
        self.menuAyuda.addAction(self.actionFormato_del_CSV)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.menuManuales.menuAction())
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.menuAcerca_del_proyecto.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuConectar.menuAction())
        self.menubar.addAction(self.menuVer.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Proyecto 4to"))
        self.label_20.setText(_translate("mainWindow", "Archivo cargado:"))
        self.label_19.setText(_translate("mainWindow", "Dirección:"))
        self.pushButton_cargarDir.setText(_translate("mainWindow", "Cargar"))
        self.label_18.setText(_translate("mainWindow", "Importe su archivo *.csv con los datos del acelerómetro y/o GPS aquí."))
        self.label_nombreArchivoCSV.setText(_translate("mainWindow", "<archivo.csv>"))
        self.pushButton_examDir.setText(_translate("mainWindow", "Examinar"))
        self.pushButton_CargarLabelsMedias.setText(_translate("mainWindow", "Cargar "))
        self.pushButton_LimparLabelsMedias.setText(_translate("mainWindow", "Limpiar"))
        self.groupBox_gps.setTitle(_translate("mainWindow", "GPS"))
        self.label_5.setText(_translate("mainWindow", "Posición [m]:"))
        self.label_6.setText(_translate("mainWindow", "Dato 2:"))
        self.label_7.setText(_translate("mainWindow", "Dato 3:"))
        self.label_8.setText(_translate("mainWindow", "Dato 4:"))
        self.label_gps_PosicionMedia.setText(_translate("mainWindow", "<data>"))
        self.label_gps_dato2.setText(_translate("mainWindow", "<data>"))
        self.label_gps_dato3.setText(_translate("mainWindow", "<data>"))
        self.label_gps_dato4.setText(_translate("mainWindow", "<data>"))
        self.groupBox_acc.setTitle(_translate("mainWindow", "Acelerómetro"))
        self.label_2.setText(_translate("mainWindow", "<html><head/><body><p>Aceleración [m/s<span style=\" vertical-align:super;\">2</span>]:</p></body></html>"))
        self.label_4.setText(_translate("mainWindow", "Posición [m]:"))
        self.label_3.setText(_translate("mainWindow", "Velocidad [m/s]:"))
        self.label_acc_AceleracionMedia.setText(_translate("mainWindow", "<data>"))
        self.label_acc_PosicionMedia.setText(_translate("mainWindow", "<data>"))
        self.label_acc_VelocidadMedia.setText(_translate("mainWindow", "<data>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "Valores Medios"))
        self.label_17.setText(_translate("mainWindow", "Velocidad vs tiempo."))
        self.label.setText(_translate("mainWindow", "Posición vs tiempo."))
        self.pushButton_Graficar_PosVsTiempo.setText(_translate("mainWindow", "Graficar"))
        self.label_9.setText(_translate("mainWindow", "Aceleración vs tiempo."))
        self.pushButton_Graficar_VelVsTiempo.setText(_translate("mainWindow", "Graficar"))
        self.pushButton_Graficar_AccVsTiempo.setText(_translate("mainWindow", "Graficar"))
        self.label_22.setText(_translate("mainWindow", "Nota: La variable tiempo se refiere al tiempo de ejecución."))
        self.label_10.setText(_translate("mainWindow", "Nota a programador: por ahora solo ploteo los datos del ACC."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainWindow", "Gráficas"))
        self.menuArchivo.setTitle(_translate("mainWindow", "Archivo"))
        self.menuConectar.setTitle(_translate("mainWindow", "Conectar"))
        self.menuVer.setTitle(_translate("mainWindow", "Ver"))
        self.menuAyuda.setTitle(_translate("mainWindow", "Ayuda"))
        self.menuAcerca_del_proyecto.setTitle(_translate("mainWindow", "Acerca del proyecto"))
        self.menuManuales.setTitle(_translate("mainWindow", "Manuales"))
        self.actionSalir.setText(_translate("mainWindow", "Salir"))
        self.actionExportar_Datos.setText(_translate("mainWindow", "Exportar Datos"))
        self.actionImportar_CSV.setText(_translate("mainWindow", "Importar CSV"))
        self.actionMinimizar.setText(_translate("mainWindow", "Minimizar"))
        self.actionTamanio_Completo.setText(_translate("mainWindow", "Tamaño Completo"))
        self.actionExportar_Graficas.setText(_translate("mainWindow", "Exportar "))
        self.actionIr_a_carpeta_fuente.setText(_translate("mainWindow", "Ir a carpeta fuente"))
        self.actionManual_de_usuario.setText(_translate("mainWindow", "Manual de usuario"))
        self.actionIdea_Fuerza.setText(_translate("mainWindow", "Idea Fuerza"))
        self.actionInforme.setText(_translate("mainWindow", "Informe"))
        self.actionIr_carpeta_fuente.setText(_translate("mainWindow", "Ir a carpeta fuente"))
        self.actionNotas.setText(_translate("mainWindow", "Notas"))
        self.actionManual_tecnico.setText(_translate("mainWindow", "Manual tecnico"))
        self.actionManual_de_app.setText(_translate("mainWindow", "Manual de app"))
        self.actionConfiguracion.setText(_translate("mainWindow", "Configuración"))
        self.actionEjemplo_de_formato_csv.setText(_translate("mainWindow", "Ejemplo de formato .csv"))
        self.actionFormato_del_CSV.setText(_translate("mainWindow", "Formato del CSV"))

